export './login/route.dart' show loginRoute;
export './creation/route.dart' show creationRoute;
export './vcaptcha/route.dart' show vcaptchaRoute;
export './vpassword/route.dart' show vpasswordRoute;
export './upassword/route.dart' show upasswordRoute;
export './about/route.dart' show aboutRoute;
export './webview/route.dart' show webviewRoute;
export './note/route.dart' show noteRoute;
export './profile/route.dart' show profileRoute;
